service: medication-app-frontend

frameworkVersion: '4'

provider:
  name: aws
  runtime: nodejs20.x
  region: us-east-1

plugins:
  - serverless-s3-sync

custom:
  s3Sync:
    - bucketName: medication-app-spa-bucket
      localDir: dist  # your Vite build output folder

resources:
  Resources:
    FrontendBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: medication-app-spa-bucket
        WebsiteConfiguration:
          IndexDocument: index.html
          ErrorDocument: index.html

    CDNDistribution:
      Type: AWS::CloudFront::Distribution
      Properties:
        DistributionConfig:
          Origins:
            - DomainName: !GetAtt FrontendBucket.DomainName
              Id: S3Origin
              S3OriginConfig: {}
          Enabled: true
          DefaultRootObject: index.html
          DefaultCacheBehavior:
            TargetOriginId: S3Origin
            ViewerProtocolPolicy: redirect-to-https
            AllowedMethods: ["GET", "HEAD"]
            CachePolicyId: 658327ea-f89d-4fab-a63d-7e88639e58f6 # AWS Managed CachingOptimized Policy
          ViewerCertificate:
            CloudFrontDefaultCertificate: true

